---
   - name: Configuring Docker Repository
     yum_repository:
       name: Docker
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/" 
       gpgcheck: no
     register: x
     become: true

   - name: installing python
     command: "yum install python3 -y"
     become: true
  
   
   - name: Checking Configuration Status
     debug:
       var: x.failed
     become: true

   - name: Installing Docker
     package:
       name: "docker-ce-18.06.3.ce-3.el7.x86_64"
       state: present
     register: y
     become: true

   - name: Checking Install Status
     debug:
       var: y.failed

   - name: Starting Docker Daemon
     service:
       name: docker
       state: started
       enabled: yes
     when: y.failed == false
     become: true

   - name: Install
     command: "pip3 install docker-py"    
     become: true


   - name: Pull a Docker Image
     docker_image: 
        name: techcrew5/sklearn:latest
        tag: latest
        source: pull
     register: z
     become: true

   - name: Checking Pull Status
     debug: 
       var: z
    
   - name: Creating a Persistent Volume Dir
     file:
       path: "/root/mlops"
       state: directory
     become: true
   

   - name: Launching Container for Web-App
     when: z.failed == false
     docker_container:
       name: web-server
       image: techcrew5/sklearn:latest
       state: started
       exposed_ports:
         - "8080"
         - "5000"
       ports:
         - "8888:8080"
         - "1234:5000"
       volumes: 
         - /root/mlops:/root/mlops/
     become: true

